{
 "title": "Home",
 "description": "Distribuição das FCTs no Serpro",
 "time": { "from": "2020-01-01T00:00:00.000Z", "to": "2024-12-01T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "competencia",
    "label": "Competência",
    "query": "SELECT DISTINCT on (competencia)\n    TO_CHAR(competencia, 'MM/YYYY') AS competencia_formatada\nFROM \n    gratificacao\nORDER BY \n    competencia DESC;"
   },
   { "name": "zero", "label": "Incluir FCT Zerada", "query": "Sim, Não" },
   {
    "name": "sigla_regional",
    "label": "Regional",
    "query": "SELECT DISTINCT on (sigla_regional) sigla_regional    \nFROM \n    gratificacao\nWHERE competencia = TO_DATE('$competencia', 'MM/YYYY');"
   },
   {
    "name": "diretoria",
    "label": "Diretoria",
    "query": "SELECT DISTINCT on (diretoria) diretoria FROM gratificacao\nWHERE competencia = TO_DATE('$competencia', 'MM/YYYY');"
   },
   {
    "name": "superintendencia",
    "label": "Superintendência",
    "query": "SELECT DISTINCT on (superintendencia) superintendencia FROM gratificacao\nWHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)     \n    AND\n    diretoria IN ($diretoria) "
   },
   {
    "name": "lotacao_hierarquica",
    "label": "Lotação",
    "query": "SELECT DISTINCT on (lotacao_hierarquica) lotacao_hierarquica FROM gratificacao\nWHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)     \n    AND\n    diretoria IN ($diretoria)      \n    AND\n    superintendencia IN ($superintendencia)"
   },
   {
    "name": "cargo",
    "label": "Cargo",
    "query": "SELECT DISTINCT on (cargo) cargo FROM gratificacao\nWHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)     \n    AND\n    diretoria IN ($diretoria)  "
   },
   { "name": "matricula", "label": "Matrícula" }
  ]
 },
 "panels": [
  { "title": "Dados Filtrados", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total de Registros para a competência $competencia",
   "type": "stat",
   "description": "<br>\nFiltros: <br>\n- Competência <br>\n- Incluir FCT Zerad: $zero <br>\n- Regional <br>\n- Diretoria <br>\n- Superintendência <br>\n- Lotação  <br>\n- Cargo  <br>",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)\nFROM (\n    SELECT DISTINCT ON (competencia, matricula)\n        competencia, matricula\n    FROM gratificacao\n    WHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END   \n    AND\n    sigla_regional IN ($sigla_regional)   \n    AND diretoria IN ($diretoria)       \n    AND superintendencia IN ($superintendencia)      \n    AND lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND cargo IN ($cargo)\n    ORDER BY competencia DESC, matricula ASC\n) AS subquery;\n"
    }
   ]
  },
  {
   "title": "Média da FCT de acordo com os filtros",
   "type": "stat",
   "description": "Filtros: <br>\n- Competência <br>\n- Incluir FCT Zerad: $zero <br>\n- Regional <br>\n- Diretoria <br>\n- Superintendência <br>\n- Lotação  <br>\n- Cargo  <br>",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)   \n    AND\n    diretoria IN ($diretoria)   \n    AND superintendencia IN ($superintendencia)         \n    AND\n    lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND\n    cargo IN ($cargo)       "
    }
   ]
  },
  {
   "title": "FCT Máxima",
   "type": "stat",
   "description": "<br>\nFiltros: <br>\n- Competência <br>\n- Incluir FCT Zerad: $zero <br>\n- Regional <br>\n- Diretoria <br>\n- Superintendência <br>\n- Lotação  <br>\n- Cargo  <br>",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)   \n    AND\n    diretoria IN ($diretoria)  \n    AND superintendencia IN ($superintendencia)          \n    AND\n    lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND\n    cargo IN ($cargo)       "
    }
   ]
  },
  {
   "title": "FCT Mínima",
   "type": "stat",
   "description": "<br>\nFiltros: <br>\n- Competência <br>\n- Incluir FCT Zerad: $zero <br>\n- Regional <br>\n- Diretoria <br>\n- Superintendência <br>\n- Lotação  <br>\n- Cargo  <br>",
   "gridPos": { "h": 5, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MIN(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)   \n    AND\n    diretoria IN ($diretoria)      \n    AND superintendencia IN ($superintendencia)      \n    AND\n    lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND\n    cargo IN ($cargo)       "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 1 },
   "options": {
    "content": "<div style=\"padding: 5px;width: 100%; height: 100%; border: 5;background-color: #FFFACD;\">  \n  <center>\n    <b>\n    <span style=\"color:red\"> \n      💡 Atenção!  \n    </span>  \n    </b>       \n  <b> <b> \n    <br>    \n    <b style=\"color:red\"> Dados públicos obtidos através da Lei de Acesso à Informação (Lei Federal nº 12.527/11).<b>   \n      <br>\n      <b style=\"color:red\"> Obs.: Últimos 5 anos. <br> Empresa não disponibilizou muitas informações, como das chefias, uma nova solicitação foi realizada.<b>      \n</div>\n\n\n"
   }
  },
  {
   "title": "Dados de acordo com os filtros",
   "type": "table",
   "description": "Filtros: <br>\n- Competência <br>\n- Incluir FCT Zerad: $zero <br>\n- Regional <br>\n- Diretoria <br>\n- Superintendência <br>\n- Lotação  <br>\n- Cargo  <br>",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT competencia, matricula, sigla_regional, diretoria, \n        superintendencia,\n        lotacao_hierarquica, cargo, nivel_fca_fct_gfe, \n    valor_fca_fct_gfe, data_designacao_fct, data_destituicao_fct\n    FROM gratificacao\n    WHERE \n    '$matricula' = ''\n    AND\n    competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)     \n    AND\n    diretoria IN ($diretoria) \n    AND superintendencia IN ($superintendencia)      \n    AND\n    lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND\n    cargo IN ($cargo)    \n    ORDER BY competencia DESC, sigla_regional asc, diretoria asc, lotacao_hierarquica asc, nivel_fca_fct_gfe desc, cargo ASC, matricula asc\n    "
    },
    {
     "rawSql": "SELECT competencia, matricula, sigla_regional, diretoria, \n        superintendencia,\n        lotacao_hierarquica, cargo, nivel_fca_fct_gfe, \n    valor_fca_fct_gfe, data_designacao_fct, data_destituicao_fct\n    FROM gratificacao\n    WHERE '$matricula' != ''\n    AND\n    LPAD(matricula::TEXT, 10, '0') = LPAD('$matricula'::TEXT, 10, '0');\n"
    }
   ]
  },
  {
   "title": "Média histórica das Gratificações",
   "type": "timeseries",
   "description": "Todas as competências. \n\nFiltros: <br>\n- Incluir FCT Zerad: $zero",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT competencia as time, AVG(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE \n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END            \nGROUP BY 1\norder by 1 asc   ;\n    "
    }
   ]
  },
  {
   "title": "Histórico de Gratificação por Matrícula",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  },
  {
   "title": "Salto de gratificação acima de 3 níveis",
   "type": "table",
   "description": "Obs.: Entrada de novos concursados também tem salto acima de 4 níveis\n<br>\nFiltros:\n- Regional <br>\n- Diretoria <br>\n- Superintendencia <br>\n- Lotação  <br>\n- Cargo  <br>",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "WITH niveis_com_salto AS (\n    SELECT \n        competencia, matricula, sigla_regional, diretoria, \n        superintendencia,\n        lotacao_hierarquica, cargo, nivel_fca_fct_gfe, \n        valor_fca_fct_gfe, data_designacao_fct, data_destituicao_fct,\n        LAG(nivel_fca_fct_gfe) OVER (PARTITION BY matricula ORDER BY competencia) AS nivel_anterior\n    FROM \n        gratificacao\n    WHERE '$matricula' = ''\n    AND sigla_regional IN ($sigla_regional)     \n    AND diretoria IN ($diretoria) \n    AND superintendencia IN ($superintendencia)      \n    AND lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND cargo IN ($cargo)         \n)\nSELECT \n    competencia, matricula, sigla_regional, diretoria, \n    superintendencia,\n    lotacao_hierarquica, \n    cargo, \n    nivel_fca_fct_gfe, \n    valor_fca_fct_gfe, \n    data_designacao_fct, \n    data_destituicao_fct,\n    nivel_anterior,\n    (nivel_fca_fct_gfe - nivel_anterior) AS salto\nFROM \n    niveis_com_salto\nWHERE \n    (nivel_fca_fct_gfe - nivel_anterior) >= 4 -- Salto de 4 ou mais níveis\nOrder by salto desc, competencia desc, sigla_regional, diretoria, superintendencia\n \n    "
    },
    {
     "rawSql": "WITH niveis_com_salto AS (\n    SELECT \n        competencia, matricula, sigla_regional, diretoria, \n        superintendencia,\n        lotacao_hierarquica, cargo, nivel_fca_fct_gfe, \n        valor_fca_fct_gfe, data_designacao_fct, data_destituicao_fct,\n        LAG(nivel_fca_fct_gfe) OVER (PARTITION BY matricula ORDER BY competencia) AS nivel_anterior\n    FROM \n        gratificacao\n    WHERE '$matricula' != ''\n    AND\n    LPAD(matricula::TEXT, 10, '0') = LPAD('$matricula'::TEXT, 10, '0')\n)\nSELECT \n    competencia, matricula, sigla_regional, diretoria, \n    superintendencia,\n    lotacao_hierarquica, \n    cargo, \n    nivel_fca_fct_gfe, \n    valor_fca_fct_gfe, \n    data_designacao_fct, \n    data_destituicao_fct,\n    nivel_anterior,\n    (nivel_fca_fct_gfe - nivel_anterior) AS salto\nFROM \n    niveis_com_salto\nWHERE \n    (nivel_fca_fct_gfe - nivel_anterior) >= 4 -- Salto de 4 ou mais níveis\nOrder by salto desc, competencia desc, sigla_regional, diretoria, superintendencia\n \n    "
    }
   ]
  },
  {
   "title": "Histórico de nível de gratificação por matrícula $matricula",
   "type": "timeseries",
   "description": "Para visualizar o histórico por matrícula, clica na matrícula em uma das tabelas: <br>\n- Salto de gratificação acima de 3 níveis\n- Dados de acordo com os filtros\n\nOu digite diretamente na variável \"Matrícula\"",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT competencia as time, nivel_fca_fct_gfe    \n    FROM gratificacao\n    WHERE \n    LPAD(matricula::TEXT, 10, '0') = LPAD('$matricula'::TEXT, 10, '0')\n    order by 1 asc   \n    "
    }
   ]
  },
  {
   "title": "Média histórica das FCTs (Apenas para \"Salto de gratificação acima de 3 níveis\")",
   "type": "timeseries",
   "description": "Considera apenas os empregados que tiveram saltos maior ou igual a 4\n\nFiltros:\n- Regional <br>\n- Diretoria <br>\n- Superintendencia <br>\n- Lotação  <br>\n- Cargo  <br>",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "WITH niveis_com_salto AS (\n    SELECT \n        competencia, matricula, sigla_regional, diretoria, \n        superintendencia,\n        lotacao_hierarquica, cargo, nivel_fca_fct_gfe, \n        valor_fca_fct_gfe, data_designacao_fct, data_destituicao_fct,\n        LAG(nivel_fca_fct_gfe) OVER (PARTITION BY matricula ORDER BY competencia) AS nivel_anterior\n    FROM \n        gratificacao\n    WHERE \n    sigla_regional IN ($sigla_regional)     \n    AND\n    diretoria IN ($diretoria) \n    AND superintendencia IN ($superintendencia)      \n    AND\n    lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND\n    cargo IN ($cargo)         \n)\nSELECT competencia as time, AVG(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\nFROM \n    niveis_com_salto\nWHERE \n    (nivel_fca_fct_gfe - nivel_anterior) >= 4 -- Salto de 4 ou mais níveis\nGROUP BY 1\norder by 1 asc;"
    }
   ]
  },
  { "title": "FCT por Regional", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "$sigla_regional (Média Histórica)",
   "type": "timeseries",
   "description": "Filtros: <br>\n- Competência <br>\n- Incluir FCT Zerad: $zero <br>\n- Regional <br>\n- Diretoria <br>\n- Superintendência <br>\n- Lotação  <br>\n- Cargo  <br>",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 48 },
   "repeat": "sigla_regional",
   "targets": [
    {
     "rawSql": "SELECT competencia as time, AVG(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE \n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)       \nGROUP BY 1\norder by 1 asc   ;\n    "
    }
   ]
  },
  {
   "title": "$sigla_regional (Média)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 58 },
   "repeat": "sigla_regional",
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)   \n    AND\n    diretoria IN ($diretoria)    \n    AND superintendencia IN ($superintendencia)        \n    AND\n    lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND\n    cargo IN ($cargo)       "
    }
   ]
  },
  {
   "title": "$sigla_regional (Máxima)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 63 },
   "repeat": "sigla_regional",
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)   \n    AND\n    diretoria IN ($diretoria) \n    AND superintendencia IN ($superintendencia)               \n    AND\n    lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND\n    cargo IN ($cargo)       "
    }
   ]
  },
  {
   "title": "$sigla_regional (Mínima)",
   "type": "stat",
   "description": "Incluindo FCTs zeradas? $zero",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 66 },
   "repeat": "sigla_regional",
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MIN(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)   \n    AND\n    diretoria IN ($diretoria)      \n    AND superintendencia IN ($superintendencia)      \n    AND\n    lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND\n    cargo IN ($cargo)       "
    }
   ]
  },
  {
   "title": "FCT por Superintendência",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
     "options": {
      "content": "<div style=\"padding-top: 10px;width: 100%; height: 100%; border: 1;background-color: #D0D0D0; text-align: center;\">\n<h1>\n    <span style=\"font-weight:bolder;color: red;\">\n        Média Histórica\n    </span>    \n</h1>\n</div>\n\n\n"
     }
    },
    {
     "title": "$superintendencia",
     "type": "timeseries",
     "description": "Filtros: <br>\n- Competência <br>\n- Incluir FCT Zerad: $zero <br>\n- Regional <br>\n- Diretoria <br>\n- Superintendência <br>\n- Lotação  <br>\n- Cargo  <br>",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
     "repeat": "superintendencia",
     "targets": [
      {
       "rawSql": "SELECT competencia as time, AVG(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE \n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)   \n    AND\n    diretoria IN ($diretoria)    \n    AND superintendencia IN ($superintendencia)        \n    AND\n    lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND\n    cargo IN ($cargo)           \nGROUP BY 1\norder by 1 asc   ;\n    "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 56 },
     "options": {
      "content": "<div style=\"padding-top: 10px;width: 100%; height: 100%; border: 1;background-color: #D0D0D0; text-align: center;\">\n<h1>\n    <span style=\"font-weight:bolder;color: red;\">\n        Média\n    </span>    \n</h1>\n</div>\n\n\n"
     }
    },
    {
     "title": "$superintendencia (Média)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 58 },
     "repeat": "superintendencia",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT AVG(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)   \n    AND\n    diretoria IN ($diretoria)    \n    AND superintendencia IN ($superintendencia)        \n    AND\n    lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND\n    cargo IN ($cargo)    \n    order by 1 desc   "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 73 },
     "options": {
      "content": "<div style=\"padding-top: 10px;width: 100%; height: 100%; border: 1;background-color: #D0D0D0; text-align: center;\">\n<h1>\n    <span style=\"font-weight:bolder;color: red;\">\n        Máxima\n    </span>    \n</h1>\n</div>\n\n\n"
     }
    },
    {
     "title": "$superintendencia (Máxima)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 75 },
     "repeat": "superintendencia",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT MAX(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)   \n    AND\n    diretoria IN ($diretoria) \n    AND superintendencia IN ($superintendencia)               \n    AND\n    lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND\n    cargo IN ($cargo)       "
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 90 },
     "options": {
      "content": "<div style=\"padding-top: 10px;width: 100%; height: 100%; border: 1;background-color: #D0D0D0; text-align: center;\">\n<h1>\n    <span style=\"font-weight:bolder;color: red;\">\n        Mínima\n    </span>    \n</h1>\n</div>\n\n\n"
     }
    },
    {
     "title": "$superintendencia (Mínima)",
     "type": "stat",
     "description": "Incluindo FCTs zeradas? $zero",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 92 },
     "repeat": "superintendencia",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT MIN(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)   \n    AND\n    diretoria IN ($diretoria)      \n    AND superintendencia IN ($superintendencia)      \n    AND\n    lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND\n    cargo IN ($cargo)       "
      }
     ]
    }
   ]
  },
  {
   "title": "FCT por Diretoria",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "$diretoria (Média Histórica)",
     "type": "timeseries",
     "description": "Filtros: <br>\n- Competência <br>\n- Incluir FCT Zerad: $zero <br>\n- Regional <br>\n- Diretoria <br>\n- Superintendência <br>\n- Lotação  <br>\n- Cargo  <br>",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
     "repeat": "diretoria",
     "targets": [
      {
       "rawSql": "SELECT competencia as time, AVG(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE \n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    diretoria IN ($diretoria)        \nGROUP BY 1\norder by 1 asc   ;\n    "
      }
     ]
    },
    {
     "title": "$diretoria (Média)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
     "repeat": "diretoria",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT AVG(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)   \n    AND\n    diretoria IN ($diretoria)   \n    AND superintendencia IN ($superintendencia)             \n    AND\n    lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND\n    cargo IN ($cargo)       "
      }
     ]
    },
    {
     "title": "$diretoria (Máxima)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
     "repeat": "diretoria",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT MAX(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)   \n    AND    \n    diretoria IN ($diretoria)      \n    AND superintendencia IN ($superintendencia)          \n    AND\n    lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND\n    cargo IN ($cargo)       "
      }
     ]
    },
    {
     "title": "$diretoria (Mínima)",
     "type": "stat",
     "description": "Incluindo FCTs zeradas? $zero",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
     "repeat": "diretoria",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT MIN(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)   \n    AND\n    diretoria IN ($diretoria)      \n    AND superintendencia IN ($superintendencia)          \n    AND\n    lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND\n    cargo IN ($cargo)       "
      }
     ]
    }
   ]
  },
  {
   "title": "FCT por Cargo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "$cargo (Média Histórica)",
     "type": "timeseries",
     "description": "Filtros: <br>\n- Competência <br>\n- Incluir FCT Zerad: $zero <br>\n- Regional <br>\n- Diretoria <br>\n- Superintendência <br>\n- Lotação  <br>\n- Cargo  <br>",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
     "repeat": "cargo",
     "targets": [
      {
       "rawSql": "SELECT competencia as time, AVG(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE \n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    diretoria IN ($diretoria)        \nGROUP BY 1\norder by 1 asc   ;\n    "
      }
     ]
    },
    {
     "title": "$cargo (Média)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
     "repeat": "cargo",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT AVG(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)   \n    AND\n    diretoria IN ($diretoria)      \n    AND superintendencia IN ($superintendencia)          \n    AND\n    lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND\n    cargo IN ($cargo)       "
      }
     ]
    },
    {
     "title": "$cargo (Máxima)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 16 },
     "repeat": "cargo",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT MAX(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)   \n    AND\n    diretoria IN ($diretoria)      \n    AND superintendencia IN ($superintendencia)      \n    AND\n    lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND\n    cargo IN ($cargo)       "
      }
     ]
    },
    {
     "title": "$cargo (Mínima)",
     "type": "stat",
     "description": "Incluindo FCTs zeradas? $zero",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 19 },
     "repeat": "cargo",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT MIN(nivel_fca_fct_gfe) AS media_nivel_fca_fct_gfe\n    FROM gratificacao\n    WHERE competencia = TO_DATE('$competencia', 'MM/YYYY')\n    AND\n    CASE \n        WHEN '$zero' = 'Sim' THEN true\n        ELSE nivel_fca_fct_gfe > 0\n    END\n    AND\n    sigla_regional IN ($sigla_regional)   \n    AND\n    diretoria IN ($diretoria)      \n    AND superintendencia IN ($superintendencia)      \n    AND\n    lotacao_hierarquica IN ($lotacao_hierarquica)\n    AND\n    cargo IN ($cargo)       "
      }
     ]
    }
   ]
  }
 ]
}